/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApkPenjualan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class BuyForm extends javax.swing.JInternalFrame {
    

    /**
     * Creates new form BuyForm
     */
    public BuyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_lvl = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_har = new javax.swing.JTextField();
        kursi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btn_reg = new javax.swing.JRadioButton();
        btn_pre = new javax.swing.JRadioButton();
        btn_vip = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_kursi2 = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_change = new javax.swing.JTextField();
        btn_pro = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_res = new javax.swing.JButton();
        c_agree = new javax.swing.JCheckBox();
        txt_hak = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();

        setTitle("LOKET TIKET F1");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga/kursi");

        jLabel3.setText("Kursi");

        txt_har.setEditable(false);
        txt_har.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_har.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_harActionPerformed(evt);
            }
        });

        kursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "A", "B", "C", "D" }));
        kursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursiActionPerformed(evt);
            }
        });

        jLabel5.setText("Level tiket");

        btn_lvl.add(btn_reg);
        btn_reg.setText("Reguler");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        btn_lvl.add(btn_pre);
        btn_pre.setText("Premium");
        btn_pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preActionPerformed(evt);
            }
        });

        btn_lvl.add(btn_vip);
        btn_vip.setText("VIP");
        btn_vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vipActionPerformed(evt);
            }
        });

        jLabel6.setText("Jumlah Kursi");

        jLabel7.setText("Total bayar (IDR)");

        jLabel8.setText("Bayar (IDR)");

        jLabel9.setText("Kembalian (IDR)");

        txt_kursi2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_total.setEditable(false);
        txt_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_bayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_change.setEditable(false);
        txt_change.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btn_pro.setText("Proses");
        btn_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proActionPerformed(evt);
            }
        });

        btn_save.setText("Simpan");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_res.setText("Reset");
        btn_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resActionPerformed(evt);
            }
        });

        c_agree.setText("Silahkan centang apabila anda telah yakin menyimpan");
        c_agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_agreeActionPerformed(evt);
            }
        });

        txt_hak.setEditable(false);
        txt_hak.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("*silahkan pilih kursi dan jumlah terlebih dahulu");

        jLabel10.setText("*tambahan sesuai level");

        jLabel11.setText("masukkan jemlah pembayaran anda");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "*NOTE", "Fasilitas tiap Level Tiket", "1. Reguler: Snack dan minuman", "2. Premium: Snack, minuman dan merchandise", "3. VIP: Snack, minuman, lunch/dinner, merchandise, exclusive fan meet" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel12.setText("LOKET PEMESANAN TIKET F1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_har, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kursi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(txt_kursi2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_pro)
                        .addGap(18, 18, 18)
                        .addComponent(btn_save)
                        .addGap(18, 18, 18)
                        .addComponent(btn_res))
                    .addComponent(c_agree)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_reg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_vip))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_hak, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_total)
                                .addComponent(txt_bayar)
                                .addComponent(txt_change, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_kursi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_reg)
                                    .addComponent(btn_pre)
                                    .addComponent(btn_vip))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_hak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_har, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(c_agree)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_pro)
                            .addComponent(btn_save)
                            .addComponent(btn_res)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_harActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_harActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_harActionPerformed

    private void kursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursiActionPerformed
        switch(kursi.getSelectedIndex()){
            case 0:
                txt_har.setText("");
                btn_lvl.clearSelection();
                txt_bayar.setText("");
                txt_change.setText("");
                c_agree.setSelected(false);
                break;
            case 1:
                txt_har.setText("1200000");
                btn_lvl.clearSelection();
                txt_bayar.setText("");
                txt_change.setText("");
                c_agree.setSelected(false);
                break;
            case 2:
                txt_har.setText("1500000");
                btn_lvl.clearSelection();
                txt_bayar.setText("");
                txt_change.setText("");
                c_agree.setSelected(false);
                break;
            case 3:
                txt_har.setText("1700000");
                btn_lvl.clearSelection();
                txt_bayar.setText("");
                txt_change.setText("");
                c_agree.setSelected(false);
                break;
            default:
                txt_har.setText("2000000");
                btn_lvl.clearSelection();
                txt_bayar.setText("");
                txt_change.setText("");
                c_agree.setSelected(false);
                break;
        }
   
        
    }//GEN-LAST:event_kursiActionPerformed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        // TODO add your handling code here:
        if(kursi.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "pilih kursi terlebih dahulu");
            btn_lvl.clearSelection();
        }
        else if(txt_kursi2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "pilih jumlah kursi terlebih dahulu");
            btn_lvl.clearSelection();
        }
        else {
        txt_hak.setText("300000");
        long kurs = Long.parseLong(txt_har.getText()),
                lev = Long.parseLong(txt_hak.getText()),
                jum = Long.parseLong(txt_kursi2.getText()),
                tot;
        tot = ((kurs + lev)*jum);
        txt_total.setText("" + tot);
        txt_bayar.setText("");
        txt_change.setText("");
        c_agree.setSelected(false);
        }
        
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preActionPerformed
        // TODO add your handling code here:
        if(kursi.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "pilih kursi terlebih dahulu");
            btn_lvl.clearSelection();
        }
        else if(txt_kursi2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "pilih jumlah kursi terlebih dahulu");
            btn_lvl.clearSelection();
        }
        else {
        txt_hak.setText("500000");
        long kurs = Long.parseLong(txt_har.getText()),
                lev = Long.parseLong(txt_hak.getText()),
                jum = Long.parseLong(txt_kursi2.getText()),
                tot;
        tot = ((kurs + lev)*jum);
        txt_total.setText("" + tot);
        txt_bayar.setText("");
        txt_change.setText("");
        c_agree.setSelected(false);
        }
    }//GEN-LAST:event_btn_preActionPerformed

    private void btn_vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vipActionPerformed
        // TODO add your handling code here:
        if(kursi.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "pilih kursi dan jumlahnya terlebih dahulu");
            btn_lvl.clearSelection();
        }
        else if(txt_kursi2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "pilih jumlah kursi terlebih dahulu");
            btn_lvl.clearSelection();
        }
        else {
        txt_hak.setText("1000000");
        long kurs = Long.parseLong(txt_har.getText()),
                lev = Long.parseLong(txt_hak.getText()),
                jum = Long.parseLong(txt_kursi2.getText()),
                tot;
        tot = ((kurs + lev)*jum);
        txt_total.setText("" + tot);
        txt_bayar.setText("");
        txt_change.setText("");
        c_agree.setSelected(false);
        }
    }//GEN-LAST:event_btn_vipActionPerformed

    private void btn_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resActionPerformed
        // TODO add your handling code here:
        txt_nama.setText("");
        txt_har.setText("");
        txt_hak.setText("");
        txt_total.setText("");
        txt_bayar.setText("");
        txt_change.setText("");
        txt_kursi2.setText("");
        kursi.setSelectedIndex(0);
        btn_lvl.clearSelection();
        c_agree.setSelected(false);
    }//GEN-LAST:event_btn_resActionPerformed

    private void btn_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proActionPerformed
        // TODO add your handling code here:
        if(txt_nama.getText().isEmpty() && txt_bayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi Nama dan Pembayaran terlebih dahulu");
        }
        else if(txt_nama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan isi Nama terlebih dahulu");
        }
        else if(txt_bayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silahkan bayar terlebih dahulu");
        }
        else{ 
            long 
               pay = Long.parseLong(txt_bayar.getText()),
                tot1 = Long.parseLong(txt_total.getText()),
                tot2;
        tot2 = pay - tot1;
        txt_change.setText("" + tot2);
        }
        
       
    }//GEN-LAST:event_btn_proActionPerformed

    private void c_agreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_agreeActionPerformed
        // TODO add your handling code here:
        if(txt_change.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Silahkan diproses terlebih dahulu");
        c_agree.setSelected(false);
        }
        else if(c_agree.isSelected() == true){
        JOptionPane.showMessageDialog(null, "Pesanan telah diproses");
        c_agree.setSelected(true);
        }
        else{
        JOptionPane.showMessageDialog(null, "Pesanan dibatalkan");
        c_agree.setSelected(false);
        }
    }//GEN-LAST:event_c_agreeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        if(c_agree.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Anda harus menyetujui transaksi terlebih dahulu", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            String tiklvl = null;
            if(btn_reg.isSelected()){
                tiklvl = "Reguler";
            }else if(btn_pre.isSelected()){
                tiklvl = "Premium";
            }else if(btn_vip.isSelected()){
                tiklvl = "VIP";
            }
            
            try {
                String sql = "INSERT INTO tiket (nama, kursi, jumlah_kursi, Level_tiket, harga) VALUES ('"
                        + txt_nama.getText() + "','"
                        + kursi.getSelectedItem() + "','"
                        + txt_kursi2.getText() + "','"
                        + tiklvl + "','"
                        + txt_total.getText() + "')";
                Connection conn = (Connection)KoneksiSQL.connectDatabase();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(BuyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            OptForm optform = new OptForm();
            optform.setVisible(true);
            this.getDesktopPane().add(optform);
            this.dispose();
        }
    }//GEN-LAST:event_btn_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_lvl;
    private javax.swing.JRadioButton btn_pre;
    private javax.swing.JButton btn_pro;
    private javax.swing.JRadioButton btn_reg;
    private javax.swing.JButton btn_res;
    private javax.swing.JButton btn_save;
    private javax.swing.JRadioButton btn_vip;
    private javax.swing.JCheckBox c_agree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kursi;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_change;
    private javax.swing.JTextField txt_hak;
    private javax.swing.JTextField txt_har;
    private javax.swing.JTextField txt_kursi2;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
