/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApkPenjualan;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class DataForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataForm
     */
    public DataForm() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        txt_tran = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_sel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("database");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor", "Nama", "Kursi", "Jumlah kursi", "Level tiket", "Harga (IDR)"
            }
        ));
        jScrollPane1.setViewportView(tbl_data);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 84, 701, 278));

        btn_back.setText("Kembali");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 388, -1, -1));

        txt_tran.setEditable(false);
        txt_tran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tranActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tran, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 389, 110, -1));

        jLabel1.setText("Total Transaksi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 392, -1, -1));

        txt_sel.setEditable(false);
        getContentPane().add(txt_sel, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 422, 110, -1));

        jLabel2.setText("Tiket Terjual");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 425, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel3.setText("DATA PEMESAN TIKET");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 34, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        OptForm optform = new OptForm();
        optform.setVisible(true);
        this.getDesktopPane().add(optform);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_tranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tranActionPerformed
    
    public void showTable() {
        try{
            Statement stat = (Statement)KoneksiSQL.connectDatabase().createStatement();
            String sql = "select * from tiket";
            ResultSet rs = stat.executeQuery(sql);
            DefaultTableModel tableModel;
            tableModel = (DefaultTableModel)tbl_data.getModel();
            while(rs.next()){
                tableModel.addRow(new Object[] {
                    rs.getString(1), rs.getString(2), rs.getString(3), 
                    rs.getString(4), rs.getString(5), rs.getString(6)
                } );
                long totaluang = 0, ttiket = 0;
                int totaltiket = rs.getRow();
                for(int i=0; i < totaltiket; i++){
                    long uang = Long.parseLong((String) tableModel.getValueAt(i, 5));
                    totaluang+=uang;
                    long tiket = Long.parseLong((String) tableModel.getValueAt(i, 3));
                    ttiket+=tiket;
                }
                
                txt_tran.setText("" + totaluang);
                txt_sel.setText("" + ttiket);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataForm.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_sel;
    private javax.swing.JTextField txt_tran;
    // End of variables declaration//GEN-END:variables

    
}
