/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApkPenjualan;

/**
 *
 * @author LENOVO
 */
public class OptForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form OptForm
     */
    public OptForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tkt = new javax.swing.JButton();
        btn_data = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("MENU PILIHAN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_tkt.setText("BELI TIKET");
        btn_tkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tktActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tkt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 55));

        btn_data.setText("LIAT DATA");
        btn_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 55));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOKET PENJUALAN TIKET F1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ApkPenjualan/gambar f2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 420, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tktActionPerformed
        // TODO add your handling code here:
        BuyForm buyform = new BuyForm();
        buyform.setVisible(true);
        this.getDesktopPane().add(buyform);
        this.dispose();
        
    }//GEN-LAST:event_btn_tktActionPerformed

    private void btn_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataActionPerformed
        // TODO add your handling code here:
        DataForm dataform = new DataForm();
        dataform.setVisible(true);
        this.getDesktopPane().add(dataform);
        this.dispose();
        
    }//GEN-LAST:event_btn_dataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_data;
    private javax.swing.JButton btn_tkt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
