/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ApkPenjualan;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class pertama extends javax.swing.JFrame {

    /**
     * Creates new form pertama
     */
    public pertama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        desktopne = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_in = new javax.swing.JMenuItem();
        mn_out = new javax.swing.JMenuItem();
        mn_exit = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopne.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat datang ke aplikasi pemesanan Tiket F1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("silahkan login untuk memesan tiket");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "JADWAL F1 2022", " ", "1. 20 Maret: Bahrain - Sakhir", "2. 27 Maret: Arab Saudi - Jeddah", "3. 10 April: Australia - Albert Park", "4. 24 April: Emilia Romagna - Imola", "5. 8 Mei: Miami - Miami International Autodrome", "6. 22 Mei: Spanyol - Barcelona-Catalunya", "7. 29 Mei: Monako - Monte Carlo", "8. 12 Juni: Azerbaijan - Baku", "9. 19 Juni: Kanada - Montreal", "10. 3 Juli: Inggris - Silverstone", "11. 10 Juli: Austria - Red Bull Ring", "12. 24 Juli: Prancis - Le Castellet", "13. 31 Juli: Hungaria - Hungaroring", "14. 28 Agustus: Belgia - Spa-Francorchamps", "15. 4 September: Belanda - Zandvoort", "16. 11 September: Italia - Monza", "17.  25 September: Rusia - Sochi", "18. 2 Oktober: Singapura - Marina Bay", "19. 9 Oktober: Jepang - Suzuka", "20. 23 Oktober: Austin - Circuit of The Americas", "21. 30 Oktober: Meksiko - Autodromo Hermanos Rodriguez", "22. 13 November: Brasil - Interlagos", "23. 20 November: Abu Dhabi - Yas Marina", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 348, 309));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ApkPenjualan/gambar f3.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-530, -10, 1330, 530));

        desktopne.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopneLayout = new javax.swing.GroupLayout(desktopne);
        desktopne.setLayout(desktopneLayout);
        desktopneLayout.setHorizontalGroup(
            desktopneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        desktopneLayout.setVerticalGroup(
            desktopneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("LOGIN/LOGOUT");

        mn_in.setText("LOGIN");
        mn_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_inActionPerformed(evt);
            }
        });
        jMenu1.add(mn_in);

        mn_out.setText("LOGOUT");
        mn_out.setEnabled(false);
        mn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_outActionPerformed(evt);
            }
        });
        jMenu1.add(mn_out);

        mn_exit.setText("KELUAR");
        mn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_exitActionPerformed(evt);
            }
        });
        jMenu1.add(mn_exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopne)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopne, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_inActionPerformed
        // TODO add your handling code here:
        desktopne.removeAll();
        LogForm logform = new LogForm();
        logform.setVisible(true);
        desktopne.add(logform);
        mn_in.setEnabled(false);
        mn_out.setEnabled(true);
    }//GEN-LAST:event_mn_inActionPerformed

    private void mn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_exitActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null, "Anda mau keluar?", 
                "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if (pilih == JOptionPane.OK_OPTION ){
            System.exit(0);
        } else {
            JOptionPane.getRootFrame();
        }
        
            
    }//GEN-LAST:event_mn_exitActionPerformed

    private void mn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_outActionPerformed
        // TODO add your handling code here:
        desktopne.removeAll();
        LogForm logform = new LogForm();
        logform.setVisible(true);
        desktopne.add(logform);
        mn_out.setEnabled(false);
        mn_in.setEnabled(true);
        
    }//GEN-LAST:event_mn_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pertama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pertama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pertama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pertama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pertama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mn_exit;
    private javax.swing.JMenuItem mn_in;
    private javax.swing.JMenuItem mn_out;
    // End of variables declaration//GEN-END:variables
}
